
SELECT UPPER(TABLE_CATALOG) [BANCODE_DE_DADOS],
UPPER(table_schema) [SCHEMA], 
UPPER(TABLE_NAME) [TABELA],
UPPER(COLUMN_NAME) [NOME_DA_COLUNA],
UPPER(COLUMN_DEFAULT) [VALOR_DEFAULT],
case is_nullable when 'YES' then 'TRUE' ELSE 'FALSE' END AS NULO,
UPPER(DATA_TYPE) [TIPO_DE_DADO],
CHARACTER_MAXIMUM_LENGTH [VALOR_MAXIMO],
'ALTER TABLE '+ UPPER(TABLE_CATALOG) + '.'+ UPPER(TABLE_SCHEMA) + '.'+ UPPER(TABLE_NAME) +' ADD '+UPPER(COLUMN_NAME)+' '+UPPER(DATA_TYPE) + ' '+CASE
WHEN CONVERT(VARCHAR(50),CHARACTER_MAXIMUM_LENGTH) IS NULL THEN ''
ELSE '(' + CONVERT(VARCHAR(50),CHARACTER_MAXIMUM_LENGTH) + ')'
END + CASE
WHEN COLUMN_DEFAULT IS NULL THEN ''
ELSE ' DEFAULT ' + UPPER(COLUMN_DEFAULT) + ' '
END + CASE IS_NULLABLE
WHEN 'YES' THEN ''
ELSE ' NOT NULL '
END AS COMANDO_ALTER
 FROM  recepcao.information_schema.columns where column_name like '%nome%'

