INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1000, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1001, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1002, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1003, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1004, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1005, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1006, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1007, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1008, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1009, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');
INSERT INTO XPARAM_COBOL (NUM_PROCESSO, COD_USUARIO, DATA_TELA, FLAG_INICIO_CONTR, DATA_PROCESSAMENTO, DESC_PROCESSO, PGM_CHAMADOR, FLAG_CALC_CARGA, NUM_MAX_COMMIT, COD_RESTART_INTER, FASE_ETAPA_RESTART)
                  VALUES (1010, 'ADM', '04/01/2019', 'N', '04/01/2019', 'CALCULO FINANCEIRO - ECON000B', 'ECON000B', 'N', 2500, 0, 'F');